org: mikefreno
app: freno-me-websocket
service: freno-me-websocket
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  logs:
    websocket: true

functions:
  connect:
    handler: src/connect.connect
    events:
      - websocket: $connect
  disconnect:
    handler: src/disconnect.disconnect
    events:
      - websocket: $disconnect
  updateConnection:
    handler: src/default.handler
    events:
      - websocket: $default
  createComment:
    handler: src/create_comment.handler
    events:
      - websocket: 
            route: createComment
  updateComment:
    handler: src/update_comment.handler
    events:
      - websocket: 
            route: commentUpdate
  #deleteComment:
    #handler: src/default.deleteComment
    #events:
      #- websocket:
        #route: deleteComment
  #reactionHandler:
    #handler: src/default.reactionHandler
    #events:
      #- websocket:
        #route: reactionHandler

