org: mikefreno
app: freno-me-websocket
service: freno-me-websocket
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x

functions:
  connect:
    handler: src/connect.connect
    events:
      - websocket: $connect
  disconnect:
    handler: src/disconnect.disconnect
    events:
      - websocket: $disconnect
  default:
    handler: src/default.handler
    events:
      - websocket: $default
